name: "build-pack"
on:
  push:
    branches:
      - main
jobs:
  buildPack:
    env:
      PACKED_JS_PATH: 'dist/index.js'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Pack
        run: npm run pack

      - name: Check packed js changes
        id: packedJsStatus
        run: echo "changes={$(git status ${{ env.PACKED_JS_PATH }} --porcelain)}" >> $GITHUB_OUTPUT

      - name: Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"

      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: ${{ steps.extractBranch.outputs.branch }}
  dispatch:
    needs: buildPack
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to Git Blog Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: nelson-ens/aem-eds-boilerplate
          event-type: update-submodule
